package com.pedro_a10.LojaAPI.enums;

public enum ProductType {
  ELECTRONICS,
  COMPUTERS,
  HOME_KITCHEN,
  FASHION,
  BEAUTY_PERSONAL_CARE,
  SPORTS_OUTDOORS,
  TOYS_GAMES,
  BOOKS_STATIONERY,
  FOOD_BEVERAGES,
  HEALTH,
  AUTOMOTIVE,
  TOOLS_CONSTRUCTION,
  PET_SUPPLIES
}
